development:
  adapter: postgresql
  encoding: unicode
  database: reliefdb_development
  host: localhost
  pool: 5
  username: postgres
  password: thisisapasswordmotherfucker

production:
  adapter: postgresql
  encoding: unicode
  database: reliefdb_production
  host: localhost
  pool: 5
  username: postgres
  password: "call me postgres"