development:
  adapter: postgresql
  encoding: unicode
  database: reliefdb_development
  host: localhost
  pool: 5
  username: postgres
  password: thisisapasswordmotherfucker

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>