# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 37) do

  create_table "categories", :force => true do |t|
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "lock_version",  :integer,  :default => 0
    t.column "name",          :string
    t.column "notes",         :text
    t.column "updated_by_id", :integer
  end

  create_table "categories_items", :id => false, :force => true do |t|
    t.column "category_id", :integer, :null => false
    t.column "item_id",     :integer, :null => false
  end

  create_table "conditions", :force => true do |t|
    t.column "created_at",               :datetime
    t.column "updated_at",               :datetime
    t.column "lock_version",             :integer,                :default => 0
    t.column "type",                     :string
    t.column "shelter_id",               :integer,                               :null => false
    t.column "item_id",                  :integer,                               :null => false
    t.column "notes",                    :text
    t.column "qty_needed",               :integer
    t.column "surplus_individual",       :integer
    t.column "surplus_crates",           :integer
    t.column "qty_per_crate",            :integer
    t.column "must_dispose_of_urgently", :boolean
    t.column "urgency",                  :integer
    t.column "crate_preference",         :integer
    t.column "info_source",              :text
    t.column "updated_by_id",            :integer
    t.column "can_buy_local",            :integer
    t.column "load_id",                  :integer
    t.column "packaged_as",              :string,   :limit => 20
  end

  add_index "conditions", ["item_id"], :name => "item_id"

  create_table "faq_categories", :force => true do |t|
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "updated_by_id", :integer
    t.column "lock_version",  :integer,  :default => 0
    t.column "name",          :string
    t.column "position",      :integer
  end

  create_table "faq_entries", :force => true do |t|
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "updated_by_id",   :integer
    t.column "lock_version",    :integer,  :default => 0
    t.column "title",           :string
    t.column "text",            :text
    t.column "faq_category_id", :integer,                 :null => false
    t.column "position",        :integer
  end

  create_table "histories", :force => true do |t|
    t.column "timestamp",     :datetime
    t.column "objtype",       :string
    t.column "objid",         :integer
    t.column "updated_by_id", :integer,  :null => false
    t.column "update_desc",   :text
    t.column "obj",           :text
    t.column "was_new",       :boolean
  end

  create_table "items", :force => true do |t|
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "lock_version",   :integer,  :default => 0
    t.column "name",           :string
    t.column "notes",          :text
    t.column "updated_by_id",  :integer
    t.column "qty_per_pallet", :integer
  end

  create_table "loads", :force => true do |t|
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "updated_by_id",   :integer
    t.column "lock_version",    :integer,  :default => 0
    t.column "info_source",     :text
    t.column "notes",           :text
    t.column "source_id",       :integer,                 :null => false
    t.column "destination_id",  :integer
    t.column "title",           :string
    t.column "trucker_name",    :string
    t.column "truck_reg",       :string
    t.column "status",          :integer
    t.column "ready_by",        :datetime
    t.column "etd",             :datetime
    t.column "eta",             :datetime
    t.column "transport_avail", :integer
    t.column "routing_type",    :integer
  end

  create_table "projects", :force => true do |t|
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
    t.column "lock_version",  :integer,  :default => 0
    t.column "shelter_id",    :integer
    t.column "project_name",  :string
    t.column "project_notes", :text
  end

  create_table "resources", :force => true do |t|
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "updated_by_id", :integer,                 :null => false
    t.column "lock_version",  :integer,  :default => 0
    t.column "name",          :string
    t.column "kind",          :string
    t.column "notes",         :text
  end

  create_table "resources_shelters", :id => false, :force => true do |t|
    t.column "resource_id", :integer, :null => false
    t.column "shelter_id",  :integer, :null => false
  end

  create_table "searches", :force => true do |t|
    t.column "user_id",    :integer
    t.column "save_name",  :string,   :limit => 30
    t.column "save_data",  :text
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "shelters", :force => true do |t|
    t.column "created_at",               :datetime
    t.column "updated_at",               :datetime
    t.column "lock_version",             :integer,                                             :default => 0
    t.column "state",                    :string,   :limit => 2
    t.column "parish",                   :string
    t.column "town",                     :string
    t.column "name",                     :string
    t.column "dc",                       :boolean
    t.column "main_phone",               :string
    t.column "mgt_contact",              :string
    t.column "mgt_phone",                :string
    t.column "supply_contact",           :string
    t.column "supply_phone",             :string
    t.column "address",                  :text
    t.column "notes",                    :text
    t.column "zip",                      :integer
    t.column "other_contacts",           :text
    t.column "latitude",                 :float
    t.column "longitude",                :float
    t.column "info_source",              :text
    t.column "red_cross_status",         :integer
    t.column "region",                   :string
    t.column "capacity",                 :integer
    t.column "current_population",       :integer
    t.column "updated_by_id",            :integer
    t.column "status",                   :integer
    t.column "organization",             :string
    t.column "dc_population",            :integer
    t.column "dc_shelters",              :integer
    t.column "website",                  :string
    t.column "make_payable_to",          :string
    t.column "facility_type",            :integer
    t.column "cond_updated_at",          :datetime
    t.column "cond_updated_by_id",       :integer
    t.column "dc_more",                  :integer
    t.column "hours",                    :string
    t.column "email",                    :string
    t.column "loading_dock",             :integer
    t.column "forklift",                 :integer
    t.column "workers",                  :integer
    t.column "pallet_jack",              :integer
    t.column "client_contact_name",      :string
    t.column "client_contact_address",   :string
    t.column "client_contact_phone",     :string
    t.column "client_contact_email",     :string
    t.column "waiting_list",             :integer
    t.column "areas_served",             :string
    t.column "eligibility",              :string
    t.column "is_fee_required",          :string
    t.column "fee_amount",               :decimal,               :precision => 7, :scale => 2
    t.column "payment_forms",            :string
    t.column "temp_perm",                :string
    t.column "planned_enddate",          :date
    t.column "fee_is_for",               :string
    t.column "mission",                  :text
    t.column "cat_notes",                :text
    t.column "clients_must_bring",       :string
    t.column "fee_explanation",          :string
    t.column "temp_perm_explanation",    :string
    t.column "waiting_list_explanation", :string
  end

  create_table "shelters_users", :id => false, :force => true do |t|
    t.column "shelter_id", :integer, :null => false
    t.column "user_id",    :integer, :null => false
  end

  add_index "shelters_users", ["shelter_id"], :name => "su_shelter_id"

  create_table "tasks", :force => true do |t|
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
    t.column "lock_version", :integer,  :default => 0
    t.column "project_id",   :integer
    t.column "task_name",    :string
    t.column "done",         :boolean,  :default => false
    t.column "position",     :integer,  :default => 0
  end

  create_table "users", :force => true do |t|
    t.column "login",               :string
    t.column "salted_password",     :string
    t.column "email",               :string
    t.column "firstname",           :string
    t.column "lastname",            :string
    t.column "salt",                :string
    t.column "verified",            :integer,  :default => 0
    t.column "role",                :string
    t.column "security_token",      :string
    t.column "token_expiry",        :datetime
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "logged_in_at",        :datetime
    t.column "deleted",             :integer,  :default => 0
    t.column "delete_after",        :datetime
    t.column "priv_admin",          :boolean
    t.column "priv_write",          :boolean
    t.column "priv_read",           :boolean
    t.column "priv_read_sensitive", :boolean
    t.column "priv_new_shelters",   :boolean
  end

end
